import type { CollectionConfig } from 'payload'
import { publicRead, signedIn } from './Users'

/**
 * The credits graph: who did what on which title.
 *
 * This replaces the single most expensive structure in the old site. A cast
 * list was an ACF repeater flattened into wp_postmeta, so `cast_N_actor` and
 * `cast_N_character` appeared 168,117 times each — and because ACF writes a
 * shadow `_`-prefixed row for every value, that is 336,234 rows of key-value
 * strings with no foreign keys and no useful index. Rendering one film meant
 * dozens of meta lookups, which is what the 6.8 GB page cache was hiding.
 *
 * Here it is 168k rows with real relationships, indexed both ways. "Films this
 * person appeared in" and "who was in this film" are the same cheap query.
 */
export const Credits: CollectionConfig = {
  slug: 'credits',
  admin: {
    useAsTitle: 'character',
    defaultColumns: ['person', 'role', 'movie', 'tvShow', 'character'],
    group: 'Catalogue',
    description: 'Generated by the TMDB sync. Edit ordering here to curate a cast list.',
  },
  access: { read: publicRead, create: signedIn, update: signedIn, delete: signedIn },
  indexes: [
    { fields: ['movie', 'role', 'order'] },
    { fields: ['tvShow', 'role', 'order'] },
    { fields: ['person', 'role'] },
  ],
  fields: [
    {
      name: 'person',
      type: 'relationship',
      relationTo: 'people',
      required: true,
      index: true,
    },
    {
      name: 'role',
      type: 'select',
      required: true,
      index: true,
      options: [
        { label: 'Actor', value: 'actor' },
        { label: 'Director', value: 'director' },
        { label: 'Writer', value: 'writer' },
        { label: 'Composer', value: 'composer' },
        { label: 'Creator', value: 'creator' },
      ],
    },
    {
      name: 'movie',
      type: 'relationship',
      relationTo: 'movies',
      index: true,
      admin: { description: 'Set for film credits; leave empty for television.' },
    },
    {
      name: 'tvShow',
      type: 'relationship',
      relationTo: 'tv-shows',
      index: true,
    },
    {
      name: 'character',
      type: 'text',
      admin: { description: 'Actors only.' },
    },
    {
      name: 'order',
      type: 'number',
      defaultValue: 0,
      admin: { description: 'Billing order. Lower sorts first.' },
    },
  ],
  hooks: {
    beforeValidate: [
      ({ data }) => {
        // A credit belongs to exactly one title. Catching this here keeps the
        // sync honest rather than discovering orphans at render time.
        if (data && !data.movie && !data.tvShow) {
          throw new Error('A credit must reference either a movie or a TV show.')
        }
        if (data?.movie && data?.tvShow) {
          throw new Error('A credit cannot reference both a movie and a TV show.')
        }
        return data
      },
    ],
  },
}
