/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    movies: Movie;
    'tv-shows': TvShow;
    people: Person;
    credits: Credit;
    genres: Genre;
    'production-companies': ProductionCompany;
    networks: Network;
    countries: Country;
    languages: Language;
    posts: Post;
    pages: Page;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    movies: {
      credits: 'credits';
    };
    'tv-shows': {
      credits: 'credits';
    };
  };
  collectionsSelect: {
    movies: MoviesSelect<false> | MoviesSelect<true>;
    'tv-shows': TvShowsSelect<false> | TvShowsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    credits: CreditsSelect<false> | CreditsSelect<true>;
    genres: GenresSelect<false> | GenresSelect<true>;
    'production-companies': ProductionCompaniesSelect<false> | ProductionCompaniesSelect<true>;
    networks: NetworksSelect<false> | NetworksSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    languages: LanguagesSelect<false> | LanguagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "movies".
 */
export interface Movie {
  id: number;
  /**
   * Upstream identifier. Used to match records on every sync.
   */
  tmdbId: number;
  title: string;
  slug: string;
  /**
   * Path on the old site, used to redirect inbound links.
   */
  legacySlug?: string | null;
  /**
   * TMDB synopsis. Refreshed on sync — use Custom content for your own writing.
   */
  overview?: string | null;
  /**
   * Path on the TMDB image CDN, e.g. /abc123.jpg
   */
  posterPath?: string | null;
  /**
   * Path on the TMDB image CDN, e.g. /abc123.jpg
   */
  backdropPath?: string | null;
  releaseDate?: string | null;
  /**
   * Stored as minutes; formatted as hours and minutes on the page.
   */
  runtime?: number | null;
  certificate?: string | null;
  /**
   * TMDB popularity score, used for default ordering.
   */
  popularity?: number | null;
  /**
   * TMDB's own adult flag. The old site's importer ran without filtering, so a large share of the inherited catalogue is pornographic. Indexed so it can be excluded from browse, search and sitemaps.
   */
  adult?: boolean | null;
  youtubeUrl?: string | null;
  genres?: (number | Genre)[] | null;
  productionCompanies?: (number | ProductionCompany)[] | null;
  originalLanguage?: (number | null) | Language;
  countries?: (number | Country)[] | null;
  credits?: {
    docs?: (number | Credit)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Free-form editorial copy shown above the TMDB summary.
   */
  customContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  videoEmbeds?:
    | {
        videoUrl: string;
        videoTitle?: string | null;
        id?: string | null;
      }[]
    | null;
  podcasts?:
    | {
        title?: string | null;
        episodeTitle?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  articles?:
    | {
        internalLink?: boolean | null;
        post?: (number | null) | Post;
        url?: string | null;
        title?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "genres".
 */
export interface Genre {
  id: number;
  name: string;
  slug: string;
  tmdbId?: number | null;
  medium: 'movie' | 'tv' | 'both';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "production-companies".
 */
export interface ProductionCompany {
  id: number;
  name: string;
  slug: string;
  tmdbId?: number | null;
  logoPath?: string | null;
  originCountry?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "languages".
 */
export interface Language {
  id: number;
  name: string;
  slug: string;
  iso?: string | null;
  englishName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: number;
  name: string;
  slug: string;
  iso?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Generated by the TMDB sync. Edit ordering here to curate a cast list.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credits".
 */
export interface Credit {
  id: number;
  person: number | Person;
  role: 'actor' | 'director' | 'writer' | 'composer' | 'creator';
  /**
   * Set for film credits; leave empty for television.
   */
  movie?: (number | null) | Movie;
  tvShow?: (number | null) | TvShow;
  /**
   * Actors only.
   */
  character?: string | null;
  /**
   * Billing order. Lower sorts first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  /**
   * Upstream identifier. Used to match records on every sync.
   */
  tmdbId: number;
  name: string;
  slug: string;
  /**
   * Path on the old site, used to redirect inbound links.
   */
  legacySlug?: string | null;
  /**
   * Path on the TMDB image CDN, e.g. /abc123.jpg
   */
  profileImagePath?: string | null;
  knownForDepartment?: string | null;
  gender?: ('0' | '1' | '2' | '3') | null;
  birthDate?: string | null;
  deathDate?: string | null;
  placeOfBirth?: string | null;
  /**
   * Sourced from TMDB; overwritten on refresh unless edited below.
   */
  biography?: string | null;
  /**
   * Free-form editorial copy shown above the TMDB summary.
   */
  customContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  videoEmbeds?:
    | {
        videoUrl: string;
        videoTitle?: string | null;
        id?: string | null;
      }[]
    | null;
  podcasts?:
    | {
        title?: string | null;
        episodeTitle?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  articles?:
    | {
        internalLink?: boolean | null;
        post?: (number | null) | Post;
        url?: string | null;
        title?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  publishedAt?: string | null;
  featuredImage?: (number | null) | Media;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Surfaces this post on those title pages.
   */
  relatedTitles?:
    | (
        | {
            relationTo: 'movies';
            value: number | Movie;
          }
        | {
            relationTo: 'tv-shows';
            value: number | TvShow;
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tv-shows".
 */
export interface TvShow {
  id: number;
  /**
   * Upstream identifier. Used to match records on every sync.
   */
  tmdbId: number;
  title: string;
  slug: string;
  /**
   * Path on the old site, used to redirect inbound links.
   */
  legacySlug?: string | null;
  overview?: string | null;
  /**
   * Path on the TMDB image CDN, e.g. /abc123.jpg
   */
  posterPath?: string | null;
  /**
   * Path on the TMDB image CDN, e.g. /abc123.jpg
   */
  backdropPath?: string | null;
  firstAirDate?: string | null;
  lastAirDate?: string | null;
  /**
   * e.g. Returning Series, Ended, Canceled.
   */
  status?: string | null;
  numberOfSeasons?: number | null;
  numberOfEpisodes?: number | null;
  episodeRuntime?: number | null;
  popularity?: number | null;
  youtubeUrl?: string | null;
  genres?: (number | Genre)[] | null;
  networks?: (number | Network)[] | null;
  productionCompanies?: (number | ProductionCompany)[] | null;
  originalLanguage?: (number | null) | Language;
  countries?: (number | Country)[] | null;
  credits?: {
    docs?: (number | Credit)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Free-form editorial copy shown above the TMDB summary.
   */
  customContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  videoEmbeds?:
    | {
        videoUrl: string;
        videoTitle?: string | null;
        id?: string | null;
      }[]
    | null;
  podcasts?:
    | {
        title?: string | null;
        episodeTitle?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  articles?:
    | {
        internalLink?: boolean | null;
        post?: (number | null) | Post;
        url?: string | null;
        title?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "networks".
 */
export interface Network {
  id: number;
  name: string;
  slug: string;
  tmdbId?: number | null;
  logoPath?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'movies';
        value: number | Movie;
      } | null)
    | ({
        relationTo: 'tv-shows';
        value: number | TvShow;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'credits';
        value: number | Credit;
      } | null)
    | ({
        relationTo: 'genres';
        value: number | Genre;
      } | null)
    | ({
        relationTo: 'production-companies';
        value: number | ProductionCompany;
      } | null)
    | ({
        relationTo: 'networks';
        value: number | Network;
      } | null)
    | ({
        relationTo: 'countries';
        value: number | Country;
      } | null)
    | ({
        relationTo: 'languages';
        value: number | Language;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "movies_select".
 */
export interface MoviesSelect<T extends boolean = true> {
  tmdbId?: T;
  title?: T;
  slug?: T;
  legacySlug?: T;
  overview?: T;
  posterPath?: T;
  backdropPath?: T;
  releaseDate?: T;
  runtime?: T;
  certificate?: T;
  popularity?: T;
  adult?: T;
  youtubeUrl?: T;
  genres?: T;
  productionCompanies?: T;
  originalLanguage?: T;
  countries?: T;
  credits?: T;
  customContent?: T;
  videoEmbeds?:
    | T
    | {
        videoUrl?: T;
        videoTitle?: T;
        id?: T;
      };
  podcasts?:
    | T
    | {
        title?: T;
        episodeTitle?: T;
        url?: T;
        id?: T;
      };
  articles?:
    | T
    | {
        internalLink?: T;
        post?: T;
        url?: T;
        title?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tv-shows_select".
 */
export interface TvShowsSelect<T extends boolean = true> {
  tmdbId?: T;
  title?: T;
  slug?: T;
  legacySlug?: T;
  overview?: T;
  posterPath?: T;
  backdropPath?: T;
  firstAirDate?: T;
  lastAirDate?: T;
  status?: T;
  numberOfSeasons?: T;
  numberOfEpisodes?: T;
  episodeRuntime?: T;
  popularity?: T;
  youtubeUrl?: T;
  genres?: T;
  networks?: T;
  productionCompanies?: T;
  originalLanguage?: T;
  countries?: T;
  credits?: T;
  customContent?: T;
  videoEmbeds?:
    | T
    | {
        videoUrl?: T;
        videoTitle?: T;
        id?: T;
      };
  podcasts?:
    | T
    | {
        title?: T;
        episodeTitle?: T;
        url?: T;
        id?: T;
      };
  articles?:
    | T
    | {
        internalLink?: T;
        post?: T;
        url?: T;
        title?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  tmdbId?: T;
  name?: T;
  slug?: T;
  legacySlug?: T;
  profileImagePath?: T;
  knownForDepartment?: T;
  gender?: T;
  birthDate?: T;
  deathDate?: T;
  placeOfBirth?: T;
  biography?: T;
  customContent?: T;
  videoEmbeds?:
    | T
    | {
        videoUrl?: T;
        videoTitle?: T;
        id?: T;
      };
  podcasts?:
    | T
    | {
        title?: T;
        episodeTitle?: T;
        url?: T;
        id?: T;
      };
  articles?:
    | T
    | {
        internalLink?: T;
        post?: T;
        url?: T;
        title?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credits_select".
 */
export interface CreditsSelect<T extends boolean = true> {
  person?: T;
  role?: T;
  movie?: T;
  tvShow?: T;
  character?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "genres_select".
 */
export interface GenresSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tmdbId?: T;
  medium?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "production-companies_select".
 */
export interface ProductionCompaniesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tmdbId?: T;
  logoPath?: T;
  originCountry?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "networks_select".
 */
export interface NetworksSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tmdbId?: T;
  logoPath?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  iso?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "languages_select".
 */
export interface LanguagesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  iso?: T;
  englishName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  featuredImage?: T;
  excerpt?: T;
  content?: T;
  relatedTitles?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}